FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache dumb-init

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

RUN npx prisma generate

COPY tsconfig.json ./
COPY src ./src/

EXPOSE 3000 9229

ENTRYPOINT ["dumb-init", "--"]
CMD ["npm", "run", "dev"]
